id = "unicode"
name = "Unicode"
version = "0.1.5"
schema_version = 1
authors = ["Gabrielle Guimarães de Oliveira <gabrielle1guim@gmail.com>", "Ciarán Dunne"]
description = "Unicode character input for Zed via LaTeX-style completions"
repository = "https://github.com/ciaran-matthew-dunne/zed-unicode"

[language_servers.unicode]
name = "unicode"
languages = [
  "AsciiDoc",
  "Astro",
  "Bash",
  "Biome",
  "C",
  "C++",
  "Clojure",
  "CSharp",
  "CSS",
  "CSV",
  "D",
  "Dart",
  "Elixir",
  "Elm",
  "Erlang",
  "Fish",
  "FSharp",
  "GDScript",
  "Gleam",
  "Go",
  "GraphQL",
  "Haskell",
  "HEEX",
  "HTML",
  "Hy",
  "Idris",
  "Java",
  "JavaScript",
  "JSON",
  "JSONC",
  "Julia",
  "Kotlin",
  "Lambdapi",
  "LaTeX",
  "Lean",
  "Lua",
  "Markdown",
  "Nim",
  "Nix",
  "OCaml",
  "PureScript",
  "Python",
  "Racket",
  "Roc",
  "Ruby",
  "Rust",
  "Scheme",
  "SCSS",
  "Shell Script",
  "SQL",
  "Swift",
  "TOML",
  "TSX",
  "TypeScript",
  "WIT",
  "XML",
  "YAML",
  "Zig",
]
